# Generated by Django 2.0.1 on 2018-03-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='value',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_beneficiaries', to='account.Account'),
        ),
    ]
