# Generated by Django 2.0.1 on 2018-03-28 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180325_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=130)),
                ('seen', models.BooleanField(default=False)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Due')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='account.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='account.Account')),
            ],
        ),
    ]
