# Generated by Django 2.0.1 on 2018-03-29 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='latest_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
