# Generated by Django 2.0.1 on 2018-03-29 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_notification_latest_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='latest_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
