# Generated by Django 2.0.1 on 2018-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_notification_latest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[('PAID', 0), ('UNPAID', 1), ('ACCEPTED', 2), ('DECLINED', 3)], default=None),
            preserve_default=False,
        ),
    ]
