# Generated by Django 2.0.1 on 2018-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
